#!/bin/bash

echo "Pilih titit yang ingin di install"
echo "  1) Windows 2019(Default)"
echo "  2) Windows 10 Super Lite SF"
echo "  3) Windows 10 Super Lite MF"
echo "  4) Windows 10 Super Lite CF"
echo "  5) Pakai link gz mu sendiri"

read -p "Pilih [1]: " PILIHOS

case "$PILIHOS" in
        1|"") PILIHOS="https://sourceforge.net/projects/nixpoin/files/windows2019DO.gz";;
        2) PILIHOS="https://master.dl.sourceforge.net/project/manyod/wedus10lite.gz?viasf=1";;
        3) PILIHOS="https://download1582.mediafire.com/lemxvneeredgyBT5P6YtAU5Dq-mikaH29djd8VnlyMcV1iM_vHJzYCiTc8V3PQkUslqgQSG0ftRJ0X2w3t1D7T4a-616-phGqQ2xKCn8894r0fdV9jKMhVYKH8N1dXMvtsZdK6e4t9F4Hg66wCzpXvuD_jcRu9_-i65_Kbr-HeW8Bw/gcxlheshfpbyigg/wedus10lite.gz";;
        4) PILIHOS="https://umbel.my.id/wedus10lite.gz";;
        5) read -p "Masukkan Link GZ mu : " PILIHOS;;
        *) echo "pilihan salah"; exit;;
esac

read -p "Masukkan password untuk akun Administrator (minimal 12 karakter): " PASSADMIN

IP4=$(curl -4 -s icanhazip.com)
GW=$(ip route | awk '/default/ { print $3 }')

DISK=$(lsblk -ndo NAME,SIZE | sort -k2 -h | tail -n1 | awk '{print $1}')
DISK="/dev/$DISK"

cat >/tmp/net.bat<<EOF
@ECHO OFF
cd.>%windir%\GetAdmin
if exist %windir%\GetAdmin (del /f /q "%windir%\GetAdmin") else (
echo CreateObject^("Shell.Application"^).ShellExecute "%~s0", "%*", "", "runas", 1 >> "%temp%\Admin.vbs"
"%temp%\Admin.vbs"
del /f /q "%temp%\Admin.vbs"
exit /b 2)
net user Administrator $PASSADMIN

for /f "tokens=3*" %%i in ('netsh interface show interface ^|findstr /I /R "Ethernet"') do (set InterfaceName=%%j)
netsh -c interface ip set address name="Ethernet" source=static address=$IP4 mask=255.255.240.0 gateway=$GW
netsh -c interface ip add dnsservers name="Ethernet" address=8.8.8.8 index=1 validate=no
netsh -c interface ip add dnsservers name="Ethernet" address=8.8.4.4 index=2 validate=no

cd /d "%ProgramData%/Microsoft/Windows/Start Menu/Programs/Startup"
del /f /q net.bat
exit
EOF

cat >/tmp/dpart.bat<<EOF
@ECHO OFF
cd.>%windir%\GetAdmin
if exist %windir%\GetAdmin (del /f /q "%windir%\GetAdmin") else (
echo CreateObject^("Shell.Application"^).ShellExecute "%~s0", "%*", "", "runas", 1 >> "%temp%\Admin.vbs"
"%temp%\Admin.vbs"
del /f /q "%temp%\Admin.vbs"
exit /b 2)

set PORT=22
netsh advfirewall firewall add rule name="Open Port 22" dir=in action=allow protocol=TCP localport=22
reg add "HKLM\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" /v PortNumber /t REG_DWORD /d 22

exit
EOF

wget --no-check-certificate "$PILIHOS" -O win.gz || exit 1

gunzip -t win.gz || exit 1

gunzip win.gz

sync

dd if=win of=$DISK bs=4M status=progress

sync

PART=$(lsblk -ln $DISK | awk 'NR==2{print $1}')
mount.ntfs-3g /dev/$PART /mnt || exit 1

cd "/mnt/ProgramData/Microsoft/Windows/Start Menu/Programs/" || exit
cd Start* || cd start*

cp -f /tmp/net.bat net.bat
cp -f /tmp/dpart.bat dpart.bat

sync

sleep 3
poweroff
